gcp_project_id                  = "labgce-424206"
gcp_service_account_key_file_path = "../credentials/labgce-service-account-key.json"
gce_instance_name               = "labgce"
gce_ssh_pub_key_file_path       = "../credentials/labgce-ssh-key.pub"
gce_instance_user               = "labgce"